FROM prom/prometheus:latest

# Копируем конфиг прямо в образ
COPY prometheus.yml /etc/prometheus/prometheus.yml

# Если у вас есть файлы правил (rules), их тоже можно скопировать
# COPY alert_rules.yml /etc/prometheus/alert_rules.yml

